version: "3.9"
services:

  back:
    build: .
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_URLS: 'http://0.0.0.0:8080'
      DatabaseSettings__DbProvider: 'postgresql'
      DatabaseSettings__ConnectionString: 'Host=localhost;Port=5432;Database=postgres;Username=postgres;Password=example;' 

  db:
    image: postgres
    restart: unless-stopped
    ports: 
    - '5432:5432'
    environment:
      POSTGRES_PASSWORD: example